/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EtudiantRouteImport } from './routes/etudiant'
import { Route as AdminFolderIdRouteImport } from './routes/admin_.$folderId'
import { Route as AdminConnaissancesRouteImport } from './routes/admin_.connaissances'
import { Route as AdminMessagesRouteImport } from './routes/admin_.messages'
import { Route as EtudiantFolderIdRouteImport } from './routes/etudiant_.$folderId'
import { Route as EtudiantAssistantRouteImport } from './routes/etudiant_.assistant'
import { Route as EtudiantMessagesRouteImport } from './routes/etudiant_.messages'
import { Route as EtudiantAssistantConversationIdRouteImport } from './routes/etudiant_.assistant_.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantRoute = EtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFolderIdRoute = AdminFolderIdRouteImport.update({
  id: '/admin_/$folderId',
  path: '/admin/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnaissancesRoute = AdminConnaissancesRouteImport.update({
  id: '/admin_/connaissances',
  path: '/admin/connaissances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin_/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantFolderIdRoute = EtudiantFolderIdRouteImport.update({
  id: '/etudiant_/$folderId',
  path: '/etudiant/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantAssistantRoute = EtudiantAssistantRouteImport.update({
  id: '/etudiant_/assistant',
  path: '/etudiant/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantMessagesRoute = EtudiantMessagesRouteImport.update({
  id: '/etudiant_/messages',
  path: '/etudiant/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantAssistantConversationIdRoute =
  EtudiantAssistantConversationIdRouteImport.update({
    id: '/etudiant_/assistant_/$conversationId',
    path: '/etudiant/assistant/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etudiant': typeof EtudiantRoute
  '/admin/$folderId': typeof AdminFolderIdRoute
  '/admin/connaissances': typeof AdminConnaissancesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/etudiant/$folderId': typeof EtudiantFolderIdRoute
  '/etudiant/assistant': typeof EtudiantAssistantRoute
  '/etudiant/messages': typeof EtudiantMessagesRoute
  '/etudiant/assistant/$conversationId': typeof EtudiantAssistantConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etudiant': typeof EtudiantRoute
  '/admin/$folderId': typeof AdminFolderIdRoute
  '/admin/connaissances': typeof AdminConnaissancesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/etudiant/$folderId': typeof EtudiantFolderIdRoute
  '/etudiant/assistant': typeof EtudiantAssistantRoute
  '/etudiant/messages': typeof EtudiantMessagesRoute
  '/etudiant/assistant/$conversationId': typeof EtudiantAssistantConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etudiant': typeof EtudiantRoute
  '/admin_/$folderId': typeof AdminFolderIdRoute
  '/admin_/connaissances': typeof AdminConnaissancesRoute
  '/admin_/messages': typeof AdminMessagesRoute
  '/etudiant_/$folderId': typeof EtudiantFolderIdRoute
  '/etudiant_/assistant': typeof EtudiantAssistantRoute
  '/etudiant_/messages': typeof EtudiantMessagesRoute
  '/etudiant_/assistant_/$conversationId': typeof EtudiantAssistantConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/etudiant'
    | '/admin/$folderId'
    | '/admin/connaissances'
    | '/admin/messages'
    | '/etudiant/$folderId'
    | '/etudiant/assistant'
    | '/etudiant/messages'
    | '/etudiant/assistant/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/etudiant'
    | '/admin/$folderId'
    | '/admin/connaissances'
    | '/admin/messages'
    | '/etudiant/$folderId'
    | '/etudiant/assistant'
    | '/etudiant/messages'
    | '/etudiant/assistant/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/etudiant'
    | '/admin_/$folderId'
    | '/admin_/connaissances'
    | '/admin_/messages'
    | '/etudiant_/$folderId'
    | '/etudiant_/assistant'
    | '/etudiant_/messages'
    | '/etudiant_/assistant_/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EtudiantRoute: typeof EtudiantRoute
  AdminFolderIdRoute: typeof AdminFolderIdRoute
  AdminConnaissancesRoute: typeof AdminConnaissancesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  EtudiantFolderIdRoute: typeof EtudiantFolderIdRoute
  EtudiantAssistantRoute: typeof EtudiantAssistantRoute
  EtudiantMessagesRoute: typeof EtudiantMessagesRoute
  EtudiantAssistantConversationIdRoute: typeof EtudiantAssistantConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant': {
      id: '/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof EtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$folderId': {
      id: '/admin_/$folderId'
      path: '/admin/$folderId'
      fullPath: '/admin/$folderId'
      preLoaderRoute: typeof AdminFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/connaissances': {
      id: '/admin_/connaissances'
      path: '/admin/connaissances'
      fullPath: '/admin/connaissances'
      preLoaderRoute: typeof AdminConnaissancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/messages': {
      id: '/admin_/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant_/$folderId': {
      id: '/etudiant_/$folderId'
      path: '/etudiant/$folderId'
      fullPath: '/etudiant/$folderId'
      preLoaderRoute: typeof EtudiantFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant_/assistant': {
      id: '/etudiant_/assistant'
      path: '/etudiant/assistant'
      fullPath: '/etudiant/assistant'
      preLoaderRoute: typeof EtudiantAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant_/messages': {
      id: '/etudiant_/messages'
      path: '/etudiant/messages'
      fullPath: '/etudiant/messages'
      preLoaderRoute: typeof EtudiantMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant_/assistant_/$conversationId': {
      id: '/etudiant_/assistant_/$conversationId'
      path: '/etudiant/assistant/$conversationId'
      fullPath: '/etudiant/assistant/$conversationId'
      preLoaderRoute: typeof EtudiantAssistantConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EtudiantRoute: EtudiantRoute,
  AdminFolderIdRoute: AdminFolderIdRoute,
  AdminConnaissancesRoute: AdminConnaissancesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  EtudiantFolderIdRoute: EtudiantFolderIdRoute,
  EtudiantAssistantRoute: EtudiantAssistantRoute,
  EtudiantMessagesRoute: EtudiantMessagesRoute,
  EtudiantAssistantConversationIdRoute: EtudiantAssistantConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
